[tool.bumpversion]
current_version = "0.10.6"
commit = true
message = "Update version {current_version} -> {new_version} [skip ci]"

[[tool.bumpversion.files]]
filename = "common/version.go"
search = "const Version = \"{current_version}\""
replace = "const Version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "README.md"
search = "{current_version}"
replace = "{new_version}"

[[tool.bumpversion.files]]
glob = "docs/*.md"
ignore_missing_version = true
search = "{current_version}"
replace = "{new_version}"
